### ISSUE TITLE
add gladiator gifs

### ISSUE THREAD

**Issue by nmrodriguez** [midd-teaching/pronunciation_clinic#1]
aquí van opciones: 

- ![](https://media.tenor.com/images/1c88e45b0755daa070df2742cab0b3d9/tenor.gif)
- ![](https://thumbs.gfycat.com/CoolLavishAlabamamapturtle-size_restricted.gif)
- ![](https://i.pinimg.com/originals/a7/d3/c7/a7d3c7fa390f300a93ae8008ffe7e704.gif)

**Comment by jvcasillas** [comment]
jaja genial! gracias

**Comment by jvcasillas** [comment]
Added to session 3 via https://github.com/midd-teaching/pronunciation_clinic/commit/8253fb8e8eb8230248d8f60d2a409cd00f729f3e 

Thanks!
